package application

import (
	"encoding/json"
	"fmt"

	col "github.com/ilius/ls-go/lscolors"
)

// Reset undoes ANSI color codes
const Reset = "\x1b[0m"

func printColorsJson() {
	b, err := json.Marshal(colors)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}

var colors = col.Colors{
	File: map[string]col.LightDark{
		"as":      {Light: col.Fg(196), Dark: col.Fg(124)},
		"asm":     {Light: col.Fg(223), Dark: col.Fg(215)},
		"bf":      {Light: col.Fg(223), Dark: col.Fg(215)},
		"c":       {Light: col.Fg(39), Dark: col.Fg(27)},
		"clj":     {Light: col.Fg(204), Dark: col.Fg(162)},
		"coffee":  {Light: col.Fg(136), Dark: col.Fg(94)},
		"cr":      {Light: col.Fg(82), Dark: col.Fg(70)},
		"cson":    {Light: col.Fg(136), Dark: col.Fg(94)},
		"css":     {Light: col.Fg(219), Dark: col.Fg(207)},
		"dart":    {Light: col.Fg(43), Dark: col.Fg(31)},
		"diff":    {Light: col.Fg(10), Dark: col.Fg(9)},
		"elm":     {Light: col.Fg(51), Dark: col.Fg(39)},
		"erl":     {Light: col.Fg(161), Dark: col.Fg(89)},
		"ex":      {Light: col.Fg(99), Dark: col.Fg(57)},
		"f":       {Light: col.Fg(208), Dark: col.Fg(94)},
		"fs":      {Light: col.Fg(45), Dark: col.Fg(32)},
		"gb":      {Light: col.Fg(43), Dark: col.Fg(29)},
		"go":      {Light: col.Fg(121), Dark: col.Fg(109)},
		"graphql": {Light: col.Fg(219), Dark: col.Fg(207)},
		"groovy":  {Light: col.Fg(223), Dark: col.Fg(215)},
		"gv":      {Light: col.Fg(141), Dark: col.Fg(99)},
		"hs":      {Light: col.Fg(99), Dark: col.Fg(57)},
		"html":    {Light: col.Fg(87), Dark: col.Fg(73)},
		"ino":     {Light: col.Fg(43), Dark: col.Fg(29)},
		"java":    {Light: col.Fg(136), Dark: col.Fg(94)},
		"jl":      {Light: col.Fg(141), Dark: col.Fg(99)},
		"js":      {Light: col.Fg(184), Dark: col.Fg(100)},
		"jsx":     {Light: col.Fg(87), Dark: col.Fg(73)},
		"kt":      {Light: col.Fg(99), Dark: col.Fg(57)},
		"lock":    {Light: col.FgGray(8), Dark: col.FgGray(5)},
		"log":     {Light: col.FgGray(8), Dark: col.FgGray(5)},
		"lua":     {Light: col.Fg(39), Dark: col.Fg(27)},
		"m":       {Light: col.Fg(208), Dark: col.Fg(196)},
		"md":      {Light: col.Fg(87), Dark: col.Fg(73)},
		"ml":      {Light: col.Fg(208), Dark: col.Fg(94)},
		"nim":     {Light: col.Fg(184), Dark: col.Fg(100)},
		"php":     {Light: col.Fg(30), Dark: col.Fg(22)},
		"pl":      {Light: col.Fg(99), Dark: col.Fg(57)},
		"py":      {Light: col.Fg(34), Dark: col.Fg(28)},
		"r":       {Light: col.Fg(51), Dark: col.Fg(39)},
		"rb":      {Light: col.Fg(202), Dark: col.Fg(131)},
		"rs":      {Light: col.Fg(208), Dark: col.Fg(94)},
		"scala":   {Light: col.Fg(196), Dark: col.Fg(124)},
		"sh":      {Light: col.Fg(164), Dark: col.Fg(90)},
		"sol":     {Light: col.Fg(39), Dark: col.Fg(27)},
		"sql":     {Light: col.Fg(193), Dark: col.Fg(148)},
		"svelte":  {Light: col.Fg(208), Dark: col.Fg(196)},
		"swift":   {Light: col.Fg(223), Dark: col.Fg(215)},
		"vim":     {Light: col.Fg(34), Dark: col.Fg(28)},
		"vue":     {Light: col.Fg(43), Dark: col.Fg(29)},
		"xml":     {Light: col.Fg(87), Dark: col.Fg(73)},
		"zig":     {Light: col.Fg(184), Dark: col.Fg(100)},
		"run":     {Light: col.Fg(1), Dark: col.Fg(1)},
		"exe":     {Light: col.Fg(1), Dark: col.Fg(1)},

		"sharedlib": {Light: col.Fg(206), Dark: col.Fg(163)},

		"compiled":  {Light: col.FgGray(8), Dark: col.FgGray(5)},
		"compress":  {Light: col.Fg(196), Dark: col.Fg(124)},
		"document":  {Light: col.Fg(196), Dark: col.Fg(124)},
		"media":     {Light: col.Fg(141), Dark: col.Fg(99)},
		col.DEFAULT: {Light: col.FgGray(23), Dark: col.FgGray(12)},
	},
	Size: map[string]*col.Style{
		"B": col.Fg(27),
		"K": col.Fg(33),
		"M": col.Fg(81),
		"G": col.Fg(123),
		"T": col.Fg(159),
	},
	Time: col.TimeColors{
		Year:        col.Fg(3),
		Number:      col.Fg(2),
		NumberColon: col.Fg(10),
		NumberSlash: col.Fg(249),
		Word:        col.Fg(4),
	},
	Dir: col.DirColors{
		Name:       &col.Style{Fg: col.Gray(23), Bg: 18, Bold: true},
		Ext:        col.Fg(105),
		HiddenName: &col.Style{Fg: col.Gray(23), Bg: 17, Bold: true},
		HiddenExt:  col.Fg(105),
	},
	Tabular: &col.TabularColors{
		FolderHeader: col.FolderHeaderColors{
			Arrow:      col.Fg(136),
			Main:       col.BgGray(2).SetFg(136),
			Slash:      col.FgGray(5),
			LastFolder: col.Fg(226).SetBold(),
			Error:      col.Bg(196).SetFg(226),
		},
		TableHeader: col.Fg(4),
	},
	Html: &col.HtmlColors{
		Default: col.Bg(col.Gray(1)).SetFg(15),
		FolderHeader: col.FolderHeaderColors{
			Arrow:      col.Fg(136),
			Main:       col.BgGray(2).SetFg(136),
			Slash:      col.FgGray(5),
			LastFolder: col.Fg(226).SetBold(),
			Error:      col.Bg(196).SetFg(226),
		},
		TableHeader: col.Fg(4),
	},
	Link: col.LinkColors{
		Name:    col.Fg(46).SetBold(),
		NameDir: &col.Style{Bg: 18, Fg: 51, Bold: true},
		Arrow:   col.Fg(53),
		Path:    col.Fg(164),
		Broken:  col.Fg(196),
	},
	Device: &col.Style{Bg: col.Gray(3), Fg: 220, Bold: true},
	Socket: &col.Style{Fg: 15, Bg: 53, Bold: true},
	Pipe:   &col.Style{Fg: 15, Bg: 94, Bold: true},
	Stats: col.StatsColors{
		Text:   &col.Style{Bg: col.Gray(2), Fg: col.Gray(15)},
		Number: col.Fg(24),
		MS:     col.Fg(39),
	},
	Perm: col.PermColors{
		User: map[string]*col.Style{
			rootUserName: col.Fg(198),
			"daemon":     col.Fg(173),
			col.SELF:     col.Fg(40),
			col.DEFAULT:  col.Fg(37),
		},
		Group: map[string]*col.Style{
			"wheel":     col.Fg(124),
			"staff":     col.Fg(28),
			"admin":     col.Fg(100),
			col.DEFAULT: col.Fg(90),
		},
		Other: map[string]*col.Style{
			col.DEFAULT: {Bg: col.Gray(2), Fg: col.Gray(15)},
		},
	},
	Expr: col.ExprColors{
		String:  &col.Style{},
		Integer: col.Fg(27),
		Float:   col.Fg(207),
		Time:    col.Fg(11),
	},
}

var FileAliases = map[string]string{
	"s":    "asm",
	"b":    "bf",
	"c++":  "c",
	"cc":   "c",
	"cpp":  "c",
	"cs":   "c",
	"cxx":  "c",
	"d":    "c",
	"h":    "c",
	"h++":  "c",
	"hh":   "c",
	"hpp":  "c",
	"hxx":  "c",
	"pxd":  "c",
	"cljc": "clj",
	"cljs": "clj",

	"class": "compiled",
	"elc":   "compiled",
	"hi":    "compiled",
	"o":     "compiled",
	"pyc":   "compiled",

	"so":  "sharedlib",
	"bin": "sharedlib",
	"dll": "sharedlib",

	"7z":       "compress",
	"Z":        "compress",
	"bz2":      "compress",
	"deb":      "compress",
	"dmg":      "compress",
	"dpkg":     "compress",
	"gz":       "compress",
	"iso":      "compress",
	"jar":      "compress",
	"lzma":     "compress",
	"par":      "compress",
	"rar":      "compress",
	"rpm":      "compress",
	"tar":      "compress",
	"tc":       "compress",
	"tgz":      "compress",
	"txz":      "compress",
	"whl":      "compress",
	"xz":       "compress",
	"z":        "compress",
	"zip":      "compress",
	"less":     "css",
	"sass":     "css",
	"scss":     "css",
	"styl":     "css",
	"djvu":     "document",
	"doc":      "document",
	"docx":     "document",
	"dvi":      "document",
	"eml":      "document",
	"fotd":     "document",
	"odp":      "document",
	"odt":      "document",
	"pdf":      "document",
	"ppt":      "document",
	"pptx":     "document",
	"rtf":      "document",
	"xls":      "document",
	"xlsx":     "document",
	"f03":      "f",
	"f77":      "f",
	"f90":      "f",
	"f95":      "f",
	"for":      "f",
	"fpp":      "f",
	"ftn":      "f",
	"fsi":      "fs",
	"fsscript": "fs",
	"fsx":      "fs",
	"dna":      "gb",
	"gsh":      "groovy",
	"gvy":      "groovy",
	"gy":       "groovy",
	"htm":      "html",
	"xhtml":    "html",
	"bson":     "js",
	"json":     "js",
	"mjs":      "js",
	"ts":       "js",
	"tsx":      "jsx",
	"cjsx":     "jsx",
	"mat":      "m",
	"markdown": "md",
	"mkd":      "md",
	"rst":      "md",
	"sml":      "ml",
	"mli":      "ml",
	"aac":      "media",
	"alac":     "media",
	"audio":    "media",
	"avi":      "media",
	"bmp":      "media",
	"cbr":      "media",
	"cbz":      "media",
	"eps":      "media",
	"flac":     "media",
	"flv":      "media",
	"gif":      "media",
	"ico":      "media",
	"image":    "media",
	"jpeg":     "media",
	"jpg":      "media",
	"m2v":      "media",
	"m4a":      "media",
	"mka":      "media",
	"mkv":      "media",
	"mov":      "media",
	"mp3":      "media",
	"mp4":      "media",
	"mpeg":     "media",
	"mpg":      "media",
	"nef":      "media",
	"ogg":      "media",
	"ogm":      "media",
	"ogv":      "media",
	"opus":     "media",
	"orf":      "media",
	"pbm":      "media",
	"pgm":      "media",
	"png":      "media",
	"pnm":      "media",
	"ppm":      "media",
	"pxm":      "media",
	"stl":      "media",
	"svg":      "media",
	"tif":      "media",
	"tiff":     "media",
	"video":    "media",
	"vob":      "media",
	"wav":      "media",
	"webm":     "media",
	"webp":     "media",
	"wma":      "media",
	"wmv":      "media",
	"xpm":      "media",
	"php3":     "php",
	"php4":     "php",
	"php5":     "php",
	"phpt":     "php",
	"phtml":    "php",
	"ipynb":    "py",
	"pickle":   "py",
	"pkl":      "py",
	"pyx":      "py",
	"bash":     "sh",
	"csh":      "sh",
	"fish":     "sh",
	"ksh":      "sh",
	"zsh":      "sh",
	"plpgsql":  "sql",
	"plsql":    "sql",
	"psql":     "sql",
	"tsql":     "sql",
	"vimrc":    "vim",
}

func init() {
	uc := colors.Perm.User
	for _, username := range platform.SystemUserNames() {
		if uc[username] == nil {
			uc[username] = col.Fg(11)
		}
	}
}
